"""
Finsage Payslip PDF Template
============================

Generates a professional, printable payslip PDF for a single employee
in a given payroll run.

Integration
-----------
    from BackEnd.Services.db_service import db_service
    from BackEnd.utils.payslip_template import render_payslip_pdf

    pdf_bytes = render_payslip_pdf(company_id, run_id, employee_id)

The returned ``bytes`` can be:
    - saved to disk (see ``save_payslip_pdf`` helper below)
    - returned directly as a Flask ``Response`` with mimetype ``application/pdf``

Layout overview
---------------
    +----------------------------------------------------+
    | [LOGO]   COMPANY NAME                              |
    |          reg / tax / vat / address / phone / email|
    +----------------------------------------------------+
    |                     PAYSLIP                        |
    |  Run No  | Period  | Pay Date  | Currency | Status |
    +----------------------------------------------------+
    |  Employee block (no, name, id, tax, dept, role)    |
    |  Bank block (bank, branch, account, type, holder)  |
    |  Eligibility block (days / hours / proration)      |
    +----------------------------------------------------+
    |  EARNINGS           | DEDUCTIONS                   |
    |  desc   amt         | desc   amt                   |
    |  ...               | ...                          |
    +----------------------------------------------------+
    |  TAXES              | EMPLOYER CONTRIBUTIONS       |
    |  desc   amt         | desc   amt                   |
    +----------------------------------------------------+
    |  GROSS PAY  | TOTAL DEDUCTIONS | TAX | NET PAY    |
    |  EMPLOYER COST  | EMPLOYER CONTRIBUTIONS          |
    +----------------------------------------------------+
    |  Footer: tax authority, tax year, generated at    |
    +----------------------------------------------------+
"""

from __future__ import annotations

import io
import os
from datetime import datetime
from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    Image,
    PageBreak,
)

# Database service
from BackEnd.Services.db_service import db_service


# ---------------------------------------------------------------------------
# System branding
# ---------------------------------------------------------------------------
# Edit these two lines to rebrand the entire payslip template.
# - SYSTEM_NAME appears in the header banner next to the logo, and in the
#   page footer ("Generated by <SYSTEM_NAME>").
# - DEFAULT_LOGO_PATH is used only when the company row has no logo_url.
#   Ships with the bundled Finsage logo (assets/finsage_logo.png next to
#   this file). Override at runtime by passing logo_path=... to the
#   render functions, or by editing the constant below.
SYSTEM_NAME = "Finsage Payroll"
SYSTEM_TAGLINE = "Payroll & HR Management"

_HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_LOGO_PATH = os.path.join(_HERE, "assets", "finsage_logo.png")


# ---------------------------------------------------------------------------
# Style palette
# ---------------------------------------------------------------------------
BRAND_PRIMARY = colors.HexColor("#1F3A5F")   # deep navy
BRAND_ACCENT = colors.HexColor("#2E86AB")    # teal-blue
BRAND_SOFT = colors.HexColor("#F4F7FA")      # light grey-blue
BRAND_BORDER = colors.HexColor("#C8D2DC")    # soft border
BRAND_TEXT = colors.HexColor("#1A1A1A")      # near-black
BRAND_MUTED = colors.HexColor("#6B7280")     # grey
BRAND_POSITIVE = colors.HexColor("#1B7F4D")  # green for net pay
BRAND_NEGATIVE = colors.HexColor("#B33A3A")  # red for deductions
BRAND_HEADER_BG = colors.HexColor("#1F3A5F")
BRAND_SUBHEADER_BG = colors.HexColor("#E8EEF4")

PAGE_W, PAGE_H = A4
LEFT_MARGIN = 12 * mm
RIGHT_MARGIN = 12 * mm
TOP_MARGIN = 10 * mm
BOTTOM_MARGIN = 12 * mm
CONTENT_WIDTH = PAGE_W - LEFT_MARGIN - RIGHT_MARGIN


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _money(value, currency: str = "LSL") -> str:
    """Format a Decimal/float/None as a currency string."""
    if value is None:
        amount_str = "0.00"
    elif isinstance(value, Decimal):
        amount_str = f"{value:,.2f}"
    elif isinstance(value, (int, float)):
        amount_str = f"{Decimal(str(value)):,.2f}"
    else:
        try:
            amount_str = f"{Decimal(str(value)):,.2f}"
        except Exception:
            amount_str = "0.00"
    return f"{currency} {amount_str}"


def _safe_str(value) -> str:
    if value is None:
        return ""
    return str(value)


def _safe_date(value) -> str:
    if not value:
        return "-"
    if isinstance(value, datetime):
        return value.strftime("%d %b %Y")
    try:
        return datetime.strptime(str(value)[:10], "%Y-%m-%d").strftime("%d %b %Y")
    except Exception:
        return str(value)


def _decimal(value) -> Decimal:
    if value is None:
        return Decimal("0")
    if isinstance(value, Decimal):
        return value
    try:
        return Decimal(str(value))
    except Exception:
        return Decimal("0")


def _load_logo(
    company: dict,
    logo_path_override: str | None = None,
    width: float = 20 * mm,
    height: float = 20 * mm,
):
    """
    Return a ReportLab Image flowable for the company logo, or None.

    Resolution order:
        1. logo_path_override argument (caller-supplied file path)
        2. company['logo_url'] (URL or local file path from DB)
        3. DEFAULT_LOGO_PATH (bundled Finsage asset)

    If none of the above resolve to a readable image, returns None and the
    caller falls back to drawing a colored square with the system initial.
    """
    candidates = []
    if logo_path_override:
        candidates.append(logo_path_override)
    if company.get("logo_url"):
        candidates.append(company["logo_url"])
    candidates.append(DEFAULT_LOGO_PATH)

    for path in candidates:
        if not path:
            continue
        # URLs are not supported by ReportLab directly — only local files.
        if path.startswith(("http://", "https://")):
            continue
        if not os.path.isfile(path):
            continue
        try:
            return Image(path, width=width, height=height)
        except Exception:
            continue
    return None


def _coalesce(*values):
    """Return the first non-None, non-empty value; else None."""
    for v in values:
        if v is None:
            continue
        if isinstance(v, str) and not v.strip():
            continue
        return v
    return None


# ---------------------------------------------------------------------------
# Paragraph styles
# ---------------------------------------------------------------------------
def _build_styles() -> dict:
    base = getSampleStyleSheet()

    styles = {
        "system_name": ParagraphStyle(
            "system_name",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            textColor=colors.white,
            leading=15,
            alignment=TA_LEFT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "system_tagline": ParagraphStyle(
            "system_tagline",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=7.5,
            textColor=colors.HexColor("#AFC3D6"),
            leading=9,
            alignment=TA_LEFT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "company_name": ParagraphStyle(
            "company_name",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=BRAND_PRIMARY,
            leading=16,
            alignment=TA_LEFT,
        ),
        "company_meta": ParagraphStyle(
            "company_meta",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            textColor=BRAND_MUTED,
            leading=11,
            alignment=TA_LEFT,
        ),
        "doc_title": ParagraphStyle(
            "doc_title",
            parent=base["Title"],
            fontName="Helvetica-Bold",
            fontSize=20,
            textColor=BRAND_PRIMARY,
            leading=24,
            alignment=TA_CENTER,
            spaceAfter=2,
        ),
        "doc_subtitle": ParagraphStyle(
            "doc_subtitle",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=9,
            textColor=BRAND_MUTED,
            leading=11,
            alignment=TA_CENTER,
        ),
        "section_header": ParagraphStyle(
            "section_header",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=9,
            textColor=colors.white,
            leading=11,
            alignment=TA_LEFT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "label": ParagraphStyle(
            "label",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=7.5,
            textColor=BRAND_MUTED,
            leading=9,
            alignment=TA_LEFT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "value": ParagraphStyle(
            "value",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            textColor=BRAND_TEXT,
            leading=10,
            alignment=TA_LEFT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "cell": ParagraphStyle(
            "cell",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            textColor=BRAND_TEXT,
            leading=10,
            alignment=TA_LEFT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "cell_right": ParagraphStyle(
            "cell_right",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=8,
            textColor=BRAND_TEXT,
            leading=10,
            alignment=TA_RIGHT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "cell_bold": ParagraphStyle(
            "cell_bold",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            textColor=BRAND_TEXT,
            leading=10,
            alignment=TA_LEFT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "cell_bold_right": ParagraphStyle(
            "cell_bold_right",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8,
            textColor=BRAND_TEXT,
            leading=10,
            alignment=TA_RIGHT,
            spaceBefore=0,
            spaceAfter=0,
        ),
        "total_label": ParagraphStyle(
            "total_label",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10,
            textColor=colors.white,
            leading=13,
            alignment=TA_LEFT,
        ),
        "total_value": ParagraphStyle(
            "total_value",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=11,
            textColor=colors.white,
            leading=14,
            alignment=TA_RIGHT,
        ),
        "net_pay_label": ParagraphStyle(
            "net_pay_label",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            textColor=colors.white,
            leading=16,
            alignment=TA_LEFT,
        ),
        "net_pay_value": ParagraphStyle(
            "net_pay_value",
            parent=base["Normal"],
            fontName="Helvetica-Bold",
            fontSize=14,
            textColor=colors.white,
            leading=17,
            alignment=TA_RIGHT,
        ),
        "footer": ParagraphStyle(
            "footer",
            parent=base["Normal"],
            fontName="Helvetica",
            fontSize=7,
            textColor=BRAND_MUTED,
            leading=9,
            alignment=TA_CENTER,
        ),
        "footnote": ParagraphStyle(
            "footnote",
            parent=base["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=7.5,
            textColor=BRAND_MUTED,
            leading=10,
            alignment=TA_LEFT,
        ),
    }
    return styles


# ---------------------------------------------------------------------------
# Block builders
# ---------------------------------------------------------------------------
def _header_block(
    payload: dict,
    styles: dict,
    logo_path_override: str | None = None,
) -> Table:
    """
    Top banner. Layout (left → right):

        +----------+-------------------+---------------------------+
        | [LOGO]   | SYSTEM NAME       |  COMPANY NAME             |
        |          | tagline           |  reg / tin / vat          |
        |          |                   |  address / phone / email  |
        +----------+-------------------+---------------------------+
        |                     PAYSLIP                              |
        |  Run No | Period | Pay Date | Currency | Status           |
        +----------------------------------------------------------+
    """
    company = payload.get("company", {}) or {}
    run = payload.get("run", {}) or {}

    # ---- Logo cell ----------------------------------------------------
    logo_img = _load_logo(company, logo_path_override=logo_path_override)
    if logo_img is not None:
        logo_cell = logo_img
    else:
        # Fallback: a navy square with the system initial (white text)
        # Drawn as a 1-cell Table with a colored background.
        initial = (SYSTEM_NAME or "F")[:1].upper()
        initial_tbl = Table(
            [[Paragraph(f'<font color="white" size="14"><b>{initial}</b></font>',
                         styles["cell"])]],
            colWidths=[20 * mm],
            rowHeights=[20 * mm],
        )
        initial_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), BRAND_PRIMARY),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("BOX", (0, 0), (-1, -1), 0.5, BRAND_PRIMARY),
        ]))
        logo_cell = initial_tbl

    # ---- System banner cell (name + tagline) ------------------------
    system_lines = [
        Paragraph(SYSTEM_NAME, styles["system_name"]),
        Paragraph(SYSTEM_TAGLINE, styles["system_tagline"]),
    ]
    system_banner = Table(
        [[system_lines[0]], [system_lines[1]]],
        colWidths=[55 * mm],
        rowHeights=[14, 10],
    )
    system_banner.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BRAND_PRIMARY),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 1),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
    ]))

    # ---- Company details cell ----------------------------------------
    # Pulls all field-name variants returned by db_service.payroll_payslip_get
    # AND the /api/companies/<id> endpoint (company_reg_no, tin, vat,
    # company_email, company_phone, physical_address, postal_address, etc.)
    company_lines = []
    name = _coalesce(
        company.get("name"),
        company.get("company_name"),
        "Company",
    )
    company_lines.append(Paragraph(name, styles["company_name"]))

    meta_bits = []
    reg = _coalesce(
        company.get("registration_number"),
        company.get("company_reg_no"),
    )
    if reg:
        meta_bits.append(f"Reg: {reg}")
    tin = _coalesce(
        company.get("tax_number"),
        company.get("tin"),
    )
    if tin:
        meta_bits.append(f"TIN: {tin}")
    vat = _coalesce(
        company.get("vat_number"),
        company.get("vat"),
    )
    if vat:
        meta_bits.append(f"VAT: {vat}")
    if meta_bits:
        company_lines.append(
            Paragraph(" &nbsp;|&nbsp; ".join(meta_bits), styles["company_meta"])
        )

    addr = _coalesce(
        company.get("address"),
        company.get("billing_address"),
        company.get("physical_address"),
        company.get("postal_address"),
    )
    if addr:
        company_lines.append(Paragraph(addr, styles["company_meta"]))

    contact_bits = []
    phone = _coalesce(
        company.get("phone"),
        company.get("company_phone"),
    )
    if phone:
        contact_bits.append(f"Tel: {phone}")
    email = _coalesce(
        company.get("email"),
        company.get("company_email"),
    )
    if email:
        contact_bits.append(f"Email: {email}")
    if contact_bits:
        company_lines.append(
            Paragraph(" &nbsp;|&nbsp; ".join(contact_bits), styles["company_meta"])
        )

    company_cell = []
    for p in company_lines:
        company_cell.append(p)

    # ---- Run info cell (right side) ----------------------------------
    run_no = _safe_str(run.get("run_no") or run.get("id"))
    period = f"{_safe_date(run.get('period_start'))} - {_safe_date(run.get('period_end'))}"
    pay_date = _safe_date(run.get("payment_date"))
    currency = run.get("currency") or "LSL"
    status = _safe_str(run.get("status")).upper()

    right_block = [
        [Paragraph("PAYSLIP", styles["doc_title"])],
        [Paragraph(f"Run No: <b>{run_no}</b> &nbsp;|&nbsp; Period: <b>{period}</b>",
                   styles["doc_subtitle"])],
        [Paragraph(
            f"Pay Date: <b>{pay_date}</b> &nbsp;|&nbsp; "
            f"Currency: <b>{currency}</b> &nbsp;|&nbsp; Status: <b>{status}</b>",
            styles["doc_subtitle"],
        )],
    ]
    right_table = Table(right_block, colWidths=[CONTENT_WIDTH * 0.40])
    right_table.setStyle(TableStyle([
        ("ALIGN", (0, 0), (-1, -1), "RIGHT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
    ]))

    # ---- Assemble header row -----------------------------------------
    # Widths: logo (20mm) + system banner (55mm) + company (~remaining) + run info
    # Total = CONTENT_WIDTH
    logo_w = 22 * mm
    banner_w = 55 * mm
    right_w = CONTENT_WIDTH * 0.40
    company_w = CONTENT_WIDTH - logo_w - banner_w - right_w

    data = [[logo_cell, system_banner, company_cell, right_table]]
    tbl = Table(
        data,
        colWidths=[logo_w, banner_w, company_w, right_w],
    )
    tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ALIGN", (0, 0), (0, 0), "CENTER"),
        ("ALIGN", (1, 0), (1, 0), "LEFT"),
        ("ALIGN", (2, 0), (2, 0), "LEFT"),
        ("ALIGN", (3, 0), (3, 0), "RIGHT"),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 1.2, BRAND_PRIMARY),
    ]))
    return tbl


def _kv_table(rows: list, col_widths: list, styles: dict) -> Table:
    """rows = [[Paragraph(label), Paragraph(value)], ...]"""
    data = []
    for row in rows:
        data.append(row)
    tbl = Table(data, colWidths=col_widths)
    tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 1),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    return tbl


def _employee_block(payload: dict, styles: dict) -> Table:
    emp = payload.get("employee", {}) or {}
    bank = emp.get("bank", {}) or {}

    currency = (payload.get("run", {}) or {}).get("currency") or "LSL"

    name = emp.get("employee_name") or " ".join(
        filter(None, [emp.get("first_name"), emp.get("last_name")])
    )

    def cell(label, value):
        return [
            Paragraph(label, styles["label"]),
            Paragraph(_safe_str(value) or "-", styles["value"]),
        ]

    # 12 fields → 4 columns × 3 rows (label/value pairs side by side)
    pairs = [
        cell("Employee No.", emp.get("employee_no")),
        cell("Full Name", name),
        cell("ID / Passport", emp.get("id_number") or emp.get("passport_number")),
        cell("Tax Number", emp.get("tax_number")),
        cell("Department", emp.get("department_name")),
        cell("Position", emp.get("position_title")),
        cell("Bank", bank.get("bank_name")),
        cell("Branch Code", bank.get("branch_code")),
        cell("Account No.", bank.get("account_number")),
        cell("Account Type", bank.get("account_type")),
        cell("Account Holder", bank.get("account_holder_name")),
        cell("Pay Currency", currency),
    ]

    # Layout: 4 columns, each column is (label, value) stacked.
    # Build rows: row 0 = labels, row 1 = values, row 2 = labels, row 3 = values...
    # Easier: 3 data rows, each row contains 4 cells, each cell is a mini-table[label,value]
    col_w = CONTENT_WIDTH / 4
    rows = []
    for i in range(0, len(pairs), 4):
        row_cells = []
        for j in range(4):
            if i + j < len(pairs):
                lbl, val = pairs[i + j]
                mini = Table([[lbl], [val]], colWidths=[col_w - 8])
                mini.setStyle(TableStyle([
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]))
                row_cells.append(mini)
            else:
                row_cells.append("")
        rows.append(row_cells)

    data = [
        [Paragraph("EMPLOYEE &amp; PAYMENT DETAILS", styles["section_header"]), "", "", ""]
    ] + rows

    tbl = Table(data, colWidths=[col_w] * 4)
    tbl.setStyle(TableStyle([
        ("SPAN", (0, 0), (-1, 0)),
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_HEADER_BG),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, 0), 3),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 3),
        ("LEFTPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 3),
        ("LEFTPADDING", (0, 1), (-1, -1), 6),
        ("RIGHTPADDING", (0, 1), (-1, -1), 6),
        ("BOX", (0, 0), (-1, -1), 0.6, BRAND_BORDER),
        ("BACKGROUND", (0, 1), (-1, -1), BRAND_SOFT),
    ]))
    return tbl


def _eligibility_block(payload: dict, styles: dict) -> Table:
    elig = payload.get("eligibility", {}) or {}

    def cell(label, value):
        return [
            Paragraph(label, styles["label"]),
            Paragraph(_safe_str(value) or "-", styles["value"]),
        ]

    pairs = [
        cell("Eligible From", _safe_date(elig.get("eligible_from"))),
        cell("Eligible To", _safe_date(elig.get("eligible_to"))),
        cell("Scheduled Days", elig.get("scheduled_days")),
        cell("Eligible Days", elig.get("eligible_days")),
        cell("Worked Days", elig.get("worked_days")),
        cell("Paid Leave Days", elig.get("paid_leave_days")),
        cell("Unpaid Days", elig.get("unpaid_days")),
        cell("Scheduled Hours", elig.get("scheduled_hours")),
        cell("Worked Hours", elig.get("worked_hours")),
        cell("Unpaid Hours", elig.get("unpaid_hours")),
        cell("Proration Method", elig.get("proration_method")),
        cell("Proration Factor", elig.get("proration_factor")),
    ]

    col_w = CONTENT_WIDTH / 4
    rows = []
    for i in range(0, len(pairs), 4):
        row_cells = []
        for j in range(4):
            if i + j < len(pairs):
                lbl, val = pairs[i + j]
                mini = Table([[lbl], [val]], colWidths=[col_w - 8])
                mini.setStyle(TableStyle([
                    ("TOPPADDING", (0, 0), (-1, -1), 0),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                    ("LEFTPADDING", (0, 0), (-1, -1), 0),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]))
                row_cells.append(mini)
            else:
                row_cells.append("")
        rows.append(row_cells)

    data = [
        [Paragraph("ELIGIBILITY &amp; PRORATION", styles["section_header"]), "", "", ""]
    ] + rows

    tbl = Table(data, colWidths=[col_w] * 4)
    tbl.setStyle(TableStyle([
        ("SPAN", (0, 0), (-1, 0)),
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_HEADER_BG),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, 0), 3),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 3),
        ("LEFTPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 1), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 3),
        ("LEFTPADDING", (0, 1), (-1, -1), 6),
        ("RIGHTPADDING", (0, 1), (-1, -1), 6),
        ("BOX", (0, 0), (-1, -1), 0.6, BRAND_BORDER),
        ("BACKGROUND", (0, 1), (-1, -1), BRAND_SOFT),
    ]))
    return tbl


def _single_line_items_block(
    title: str,
    items: list,
    currency: str,
    styles: dict,
    show_tax_flag: bool = False,
) -> Table:
    """A single self-contained table: header row + items + totals row.

    The last data row is styled as a TOTAL row showing the sum of all amounts.
    """
    total_amount = sum(
        (_decimal(it.get("amount")) for it in items), Decimal("0")
    )
    header = [
        Paragraph(title, styles["section_header"]),
        Paragraph("Description", styles["section_header"]),
        Paragraph("Qty", styles["section_header"]),
        Paragraph("Rate", styles["section_header"]),
        Paragraph("Amount", styles["section_header"]),
    ]
    if show_tax_flag:
        header.append(Paragraph("Tax", styles["section_header"]))

    data = [header]
    if not items:
        empty_row = ["-"] * len(header)
        data.append(empty_row)
    else:
        for it in items:
            row = [
                Paragraph(_safe_str(it.get("code")) or "-", styles["cell"]),
                Paragraph(_safe_str(it.get("description")) or "-", styles["cell"]),
                Paragraph(_safe_str(it.get("quantity")) or "-", styles["cell_right"]),
                Paragraph(_safe_str(it.get("rate")) or "-", styles["cell_right"]),
                Paragraph(_money(it.get("amount"), currency), styles["cell_bold_right"]),
            ]
            if show_tax_flag:
                row.append(Paragraph(
                    "Y" if it.get("taxable") else "N", styles["cell_right"]
                ))
            data.append(row)

    # total row at the bottom
    total_row = ["", Paragraph("TOTAL", styles["cell_bold"]), "", "",
                 Paragraph(_money(total_amount, currency), styles["cell_bold_right"])]
    if show_tax_flag:
        total_row.insert(-1, "")
    data.append(total_row)

    # column widths — must fit exactly inside half-content-width wrapper column
    half = CONTENT_WIDTH / 2 - 2
    if show_tax_flag:
        fixed = 10 * mm + 10 * mm + 10 * mm + 14 * mm + 8 * mm
        base_widths = [
            10 * mm,
            half - fixed,
            10 * mm,
            10 * mm,
            14 * mm,
            8 * mm,
        ]
    else:
        fixed = 10 * mm + 10 * mm + 12 * mm + 16 * mm
        base_widths = [
            10 * mm,
            half - fixed,
            10 * mm,
            12 * mm,
            16 * mm,
        ]

    # Build explicit row heights: header is taller, data rows compact, total row taller.
    n_data_rows = len(data) - 2  # exclude header (idx 0) and total row (idx -1)
    row_heights = [16] + [14] * n_data_rows + [16]

    tbl = Table(data, colWidths=base_widths, rowHeights=row_heights)
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_HEADER_BG),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 1),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
        ("LEFTPADDING", (0, 0), (-1, -1), 3),
        ("RIGHTPADDING", (0, 0), (-1, -1), 3),
        ("BOX", (0, 0), (-1, -1), 0.5, BRAND_BORDER),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, BRAND_BORDER),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, BRAND_SOFT]),
        # last row = total row, distinct background
        ("BACKGROUND", (0, -1), (-1, -1), BRAND_SUBHEADER_BG),
        ("LINEABOVE", (0, -1), (-1, -1), 0.6, BRAND_PRIMARY),
    ]
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


def _earnings_deductions_block(payload: dict, styles: dict) -> Table:
    currency = (payload.get("run", {}) or {}).get("currency") or "LSL"
    earnings = payload.get("earnings", []) or []
    deductions = payload.get("deductions", []) or []

    earnings_tbl = _single_line_items_block(
        "EARNINGS", earnings, currency, styles, show_tax_flag=False
    )
    deductions_tbl = _single_line_items_block(
        "DEDUCTIONS", deductions, currency, styles, show_tax_flag=False
    )

    half = CONTENT_WIDTH / 2 - 2
    wrapper = Table(
        [[earnings_tbl, deductions_tbl]],
        colWidths=[half, half],
    )
    wrapper.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    return wrapper


def _taxes_contrib_block(payload: dict, styles: dict) -> Table:
    currency = (payload.get("run", {}) or {}).get("currency") or "LSL"
    taxes = payload.get("taxes", []) or []
    employer = payload.get("employer_contributions", []) or []

    taxes_tbl = _single_line_items_block(
        "TAXES", taxes, currency, styles, show_tax_flag=False
    )
    employer_tbl = _single_line_items_block(
        "EMPLOYER CONTRIBUTIONS", employer, currency, styles, show_tax_flag=False
    )

    half = CONTENT_WIDTH / 2 - 2
    wrapper = Table(
        [[taxes_tbl, employer_tbl]],
        colWidths=[half, half],
    )
    wrapper.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("TOPPADDING", (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
    ]))
    return wrapper


def _totals_block(payload: dict, styles: dict) -> Table:
    """Two-column totals summary: 8 fields arranged 4×2."""
    totals = payload.get("totals", {}) or {}
    currency = (payload.get("run", {}) or {}).get("currency") or "LSL"

    def cell(label, value, value_color=BRAND_TEXT):
        val_style = styles["cell_bold_right"].clone("tmp")
        val_style.textColor = value_color
        val_style.alignment = TA_LEFT
        return [
            Paragraph(label, styles["cell_bold"]),
            Paragraph(_money(value, currency), val_style),
        ]

    left_rows = [
        cell("Basic Pay", totals.get("basic_pay")),
        cell("Gross Pay", totals.get("gross_pay"), BRAND_PRIMARY),
        cell("Taxable Income", totals.get("taxable_income")),
        cell("Employer Cost", totals.get("employer_cost"), BRAND_PRIMARY),
    ]
    right_rows = [
        cell("Employee Deductions", totals.get("employee_deductions"), BRAND_NEGATIVE),
        cell("Tax (PAYE/SDL/UIF)", totals.get("tax"), BRAND_NEGATIVE),
        cell("Total Deductions", totals.get("total_deductions"), BRAND_NEGATIVE),
        cell("Employer Contributions", totals.get("employer_contributions")),
    ]

    half = CONTENT_WIDTH / 2 - 2
    sub_w = [half * 0.6, half * 0.4]
    left_tbl = Table(left_rows, colWidths=sub_w)
    left_tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.transparent),
    ]))
    right_tbl = Table(right_rows, colWidths=sub_w)
    right_tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.transparent),
    ]))

    data = [[
        Paragraph("PAY SUMMARY", styles["section_header"]),
        Paragraph("PAY SUMMARY (cont.)", styles["section_header"]),
    ], [left_tbl, right_tbl]]

    tbl = Table(data, colWidths=[half, half])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BRAND_HEADER_BG),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, 0), 3),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 3),
        ("LEFTPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 1), (-1, 1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, 1), 4),
        ("LEFTPADDING", (0, 1), (-1, 1), 6),
        ("RIGHTPADDING", (0, 1), (-1, 1), 6),
        ("BOX", (0, 0), (-1, -1), 0.6, BRAND_BORDER),
        ("LINEAFTER", (0, 0), (0, -1), 0.6, BRAND_BORDER),
        ("BACKGROUND", (0, 1), (-1, 1), BRAND_SOFT),
    ]))
    return tbl


def _net_pay_block(payload: dict, styles: dict) -> Table:
    totals = payload.get("totals", {}) or {}
    currency = (payload.get("run", {}) or {}).get("currency") or "LSL"
    net = totals.get("net_pay")

    data = [[
        Paragraph("NET PAY", styles["net_pay_label"]),
        Paragraph(_money(net, currency), styles["net_pay_value"]),
    ]]
    tbl = Table(data, colWidths=[CONTENT_WIDTH * 0.55, CONTENT_WIDTH * 0.45])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BRAND_POSITIVE),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING", (0, 0), (-1, -1), 12),
        ("RIGHTPADDING", (0, 0), (-1, -1), 12),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
    ]))
    return tbl


def _tax_footer_block(payload: dict, styles: dict) -> Table:
    tax = payload.get("tax", {}) or {}
    calc = payload.get("calculation", {}) or {}

    left = (
        f"<b>Tax Authority Code:</b> {_safe_str(tax.get('authority_code')) or '-'}"
        f" &nbsp;|&nbsp; <b>Tax Year:</b> {_safe_str(tax.get('tax_year_label')) or '-'}"
    )
    right = (
        f"<b>Calculation Status:</b> {_safe_str(calc.get('status')) or '-'}"
    )
    if calc.get("message"):
        right += f" &nbsp;|&nbsp; <b>Message:</b> {_safe_str(calc.get('message'))}"

    data = [[
        Paragraph(left, styles["footnote"]),
        Paragraph(right, styles["footnote"]),
    ]]
    tbl = Table(data, colWidths=[CONTENT_WIDTH * 0.55, CONTENT_WIDTH * 0.45])
    tbl.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("BOX", (0, 0), (-1, -1), 0.4, BRAND_BORDER),
        ("BACKGROUND", (0, 0), (-1, -1), BRAND_SOFT),
    ]))
    return tbl


# ---------------------------------------------------------------------------
# Page decoration (footer drawn on canvas)
# ---------------------------------------------------------------------------
def _on_page(canvas, doc):
    canvas.saveState()
    # bottom rule
    canvas.setStrokeColor(BRAND_BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(LEFT_MARGIN, BOTTOM_MARGIN - 4, PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 4)
    # footer text
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(BRAND_MUTED)
    generated = datetime.now().strftime("%d %b %Y %H:%M")
    footer_left = f"Generated by {SYSTEM_NAME}  |  {generated}"
    footer_right = (
        f"Page {doc.page}  |  "
        f"This is a system-generated payslip and is valid without signature."
    )
    canvas.drawString(LEFT_MARGIN, BOTTOM_MARGIN - 12, footer_left)
    canvas.drawRightString(PAGE_W - RIGHT_MARGIN, BOTTOM_MARGIN - 12, footer_right)
    canvas.restoreState()


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------
def render_payslip_pdf(
    company_id: int,
    payroll_run_id: int,
    employee_id: int,
    logo_path: str | None = None,
) -> bytes:
    """
    Build a payslip PDF for the given employee in the given payroll run.

    Args:
        logo_path: Optional local file path to override the logo image.
            If None, falls back to ``company.logo_url`` and then the
            bundled system logo (``assets/finsage_logo.png``).

    Returns the PDF as ``bytes``.
    """
    payload = db_service.payroll_payslip_get(
        company_id,
        payroll_run_id,
        employee_id,
    )

    if not payload:
        raise ValueError(
            "Payslip payload not available. Ensure payroll has been calculated."
        )

    return _build_pdf(payload, logo_path=logo_path)


def save_payslip_pdf(
    company_id: int,
    payroll_run_id: int,
    employee_id: int,
    output_path: str,
    logo_path: str | None = None,
) -> str:
    """
    Render the payslip PDF and write it to ``output_path``.
    Returns the path written to.
    """
    pdf_bytes = render_payslip_pdf(
        company_id, payroll_run_id, employee_id, logo_path=logo_path
    )
    with open(output_path, "wb") as fh:
        fh.write(pdf_bytes)
    return output_path


def render_payslip_pdf_from_payload(
    payload: dict,
    logo_path: str | None = None,
) -> bytes:
    """
    Build a payslip PDF from an already-loaded payload dict.
    Useful for preview / testing without hitting the DB.
    """
    return _build_pdf(payload, logo_path=logo_path)


# ---------------------------------------------------------------------------
# Internal builder
# ---------------------------------------------------------------------------
def _build_pdf(payload: dict, logo_path: str | None = None) -> bytes:
    styles = _build_styles()
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=LEFT_MARGIN,
        rightMargin=RIGHT_MARGIN,
        topMargin=TOP_MARGIN,
        bottomMargin=BOTTOM_MARGIN,
        title=f"Payslip - {SYSTEM_NAME}",
        author=SYSTEM_NAME,
    )

    story = []

    # Header (logo + system name + company + run info)
    story.append(_header_block(payload, styles, logo_path_override=logo_path))
    story.append(Spacer(1, 4))

    # Employee + bank details
    story.append(_employee_block(payload, styles))
    story.append(Spacer(1, 4))

    # Eligibility & proration
    story.append(_eligibility_block(payload, styles))
    story.append(Spacer(1, 6))

    # Earnings + Deductions side-by-side
    story.append(_earnings_deductions_block(payload, styles))
    story.append(Spacer(1, 6))

    # Taxes + Employer contributions side-by-side
    story.append(_taxes_contrib_block(payload, styles))
    story.append(Spacer(1, 6))

    # Totals summary
    story.append(_totals_block(payload, styles))
    story.append(Spacer(1, 4))

    # Net pay banner
    story.append(_net_pay_block(payload, styles))
    story.append(Spacer(1, 4))

    # Tax + calculation footnote
    story.append(_tax_footer_block(payload, styles))

    doc.build(story, onFirstPage=_on_page, onLaterPages=_on_page)
    return buffer.getvalue()
